 * Debugger is active!
 * Debugger PIN: 111-709-236
127.0.0.1 - - [23/Aug/2023 08:38:08] "POST /result HTTP/1.1" 500 -
Traceback (most recent call last):
  File "c:\Users\pande\OneDrive\Desktop\code\4-github-repo-finder\app.py", line 108, in getRepo
    sorted_repos.append((i+1,result[i]["name"],result[i]["forks"]))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pande\OneDrive\Desktop\code\4-github-repo-finder\app.py", line 112, in getRepo
    return render_template('error.html',text='Error! Either the organisation name is invalid, or number of repositories was too high! Please try again.')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\pande\OneDrive\Desktop\code\4-github-repo-finder\templates\error.html", line 61, in top-level template code
    <a href='{{ url_for('display_element', element=element[0]) }}'>Go back</a>
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 466, in getitem
    return obj[argument]
           ^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'element' is undefined
127.0.0.1 - - [23/Aug/2023 08:38:08] "GET /result?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:38:08] "GET /result?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:38:08] "GET /result?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:38:20] "POST /result HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:38:20] "GET /static/style.css HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:38:24] "POST /result HTTP/1.1" 500 -
Traceback (most recent call last):
  File "c:\Users\pande\OneDrive\Desktop\code\4-github-repo-finder\app.py", line 108, in getRepo
    sorted_repos.append((i+1,result[i]["name"],result[i]["forks"]))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pande\OneDrive\Desktop\code\4-github-repo-finder\app.py", line 112, in getRepo
    return render_template('error.html',text='Error! Either the organisation name is invalid, or number of repositories was too high! Please try again.')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\pande\OneDrive\Desktop\code\4-github-repo-finder\templates\error.html", line 61, in top-level template code
    <a href='{{ url_for('display_element', element=element[0]) }}'>Go back</a>
  File "C:\Users\pande\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 466, in getitem
    return obj[argument]
           ^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'element' is undefined
127.0.0.1 - - [23/Aug/2023 08:38:24] "GET /result?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:38:24] "GET /result?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:38:25] "GET /result?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:38:39] "POST /result HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:38:39] "GET /static/style_error.css HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:38:39] "GET /static/sad2.png HTTP/1.1" 404 -
127.0.0.1 - - [23/Aug/2023 08:38:40] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:39:02] "POST /result HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:39:02] "GET /static/style_error.css HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:39:02] "GET /static/sad2.png HTTP/1.1" 404 -
127.0.0.1 - - [23/Aug/2023 08:39:43] "POST /result HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:39:43] "GET /static/style_error.css HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:39:43] "GET /static/sad2.png HTTP/1.1" 404 -
127.0.0.1 - - [23/Aug/2023 08:40:35] "POST /result HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:40:35] "GET /static/style_error.css HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:41:33] "POST /result HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:41:33] "GET /static/style_error.css HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:41:46] "POST /result HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:41:46] "GET /static/style_error.css HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:41:57] "POST /result HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:41:57] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:41:59] "GET /1 HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:41:59] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:42:04] "POST /result HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:42:04] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:42:09] "GET /1 HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:42:09] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:42:26] "POST /result HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:42:26] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:42:35] "POST /result HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:42:35] "GET /static/style_error.css HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:43:07] "POST /result HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:43:07] "GET /static/style.css HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:43:18] "POST /result HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:43:18] "GET /static/style.css HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:43:25] "POST /result HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:43:25] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [23/Aug/2023 08:43:30] "POST /result HTTP/1.1" 200 -
127.0.0.1 - - [23/Aug/2023 08:43:30] "GET /static/style_error.css HTTP/1.1" 304 -
